name: 'PR Title and Commit Message Checker'
description: 'Check PR titles and commit messages against a specified format'
inputs:
  pattern:
    description: 'Regex pattern for validating PR title or commit message'
    required: false
    default: '^(fix|feat|docs|style|refactor|pref|test|build|ci|chore|revert)(\([^)]+\))?(!)?: [\x21-\x7E]([\x20-\x7E]{0,118}[\x21-\x7E])?$'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
