name: 'PR Title Checker'
description: 'Validate PR titles against Conventional Commits specification'
author: 'Young Xu'
inputs:
  strict:
    description: 'Enable strict mode (requires lowercase description start, no period at end, imperative mood)'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
